import Head from 'next/head'
import Card from '../components/Card'
import cards from '../components/cardsData'

export default function Home() {
  return (
    <main className="w-screen min-h-screen bg-landing flex flex-col justify-center items-center gap-24 1124:gap-64 p-24 1124:p-32">
      <Head>
        <title>Bogomil Stoynov</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

    <h1 className="display text-gray-500">Projects</h1>

    <ul className="w-full 380:max-w-[540px] 1124:max-w-[1600px] flex flex-col 1124:flex-row gap-24 1124:justify-evenly 1124:gap-32">
      {cards.map(card => (
        <li key={card.name}>
          <Card
            name={card.name}
            imageSrc={card.imageSrc}
            description={card.description}
            tags={card.tags}
            codeUrl={card.codeUrl}
            liveUrl={card.liveUrl}
            videoUrl={card.videoUrl}
          />
        </li>
      ))}
    </ul>
    </main>
  )
}
